name: Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  xcode_tests:
    name: ${{ matrix.platform }} Tests (Xcode)
    runs-on: macos-latest
    needs: macos_tests
    strategy:
      fail-fast: false
      matrix:
        scheme: ['blue-triangle']
        destination:
          - "platform=iOS Simulator,OS=latest,name=iPhone 12"
          - "platform=macOS,arch=arm64"

    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: xcodebuild clean test -scheme ${{ matrix.scheme }} -destination "${{ matrix.destination }}" -resultBundlePath TestResults | xcpretty
      - name: Show Test Results
        uses: kishikawakatsumi/xcresulttool@v1.5.0
        with:
          path: TestResults.xcresult
        if: success() || failure()
